pool: AXIS-SBX-POOL


stages:
- stage: terraform_init
  displayName: init stage hai pahale
  jobs:
  - job: terraform_init
    displayName: is job mai init chal raha
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'axis-terraform-connection'
        backendAzureRmResourceGroupName: 'AXIS-SBX-POC-RG'
        backendAzureRmStorageAccountName: 'axissbxpocst01'
        backendAzureRmContainerName: 'axixpoctfstate'
        backendAzureRmKey: 'poc.tfstate'


- stage: terraform_validate
  displayName: validate stage hai pahale
  jobs:
    - job: terraform_validate
      displayName: is job mai validate chal raha
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'axis-terraform-connection'
          backendAzureRmResourceGroupName: 'AXIS-SBX-POC-RG'
          backendAzureRmStorageAccountName: 'axissbxpocst01'
          backendAzureRmContainerName: 'axixpoctfstate'
          backendAzureRmKey: 'poc.tfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'validate'
          environmentServiceNameAzureRM: 'axis-terraform-connection'


- stage: terraform_plan
  displayName: plan stage hai pahale
  jobs:
    - job: terraform_validate
      displayName: is job mai plan chal raha
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'axis-terraform-connection'
          backendAzureRmResourceGroupName: 'AXIS-SBX-POC-RG'
          backendAzureRmStorageAccountName: 'axissbxpocst01'
          backendAzureRmContainerName: 'axixpoctfstate'
          backendAzureRmKey: 'poc.tfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'validate'
          environmentServiceNameAzureRM: 'axis-terraform-connection'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'axis-terraform-connection'

- stage: terraform_apply
  displayName: apply stage hai pahale
  jobs:
    - job: terraform_apply
      displayName: is job mai plan chal raha
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'axis-terraform-connection'
          backendAzureRmResourceGroupName: 'AXIS-SBX-POC-RG'
          backendAzureRmStorageAccountName: 'axissbxpocst01'
          backendAzureRmContainerName: 'axixpoctfstate'
          backendAzureRmKey: 'poc.tfstate'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'validate'
          environmentServiceNameAzureRM: 'axis-terraform-connection'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          environmentServiceNameAzureRM: 'axis-terraform-connection'



