pool: AXIS-SBX-POOL

stages:

- stage:
  displayName: tera_init

  jobs:
  - job: terraforminit
    displayName: tera_init

    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        backendServiceArm: 'axis-terraform-connection'
        backendAzureRmResourceGroupName: 'axis-sbx-poc-rg'
        backendAzureRmStorageAccountName: 'axissbxpocst01'
        backendAzureRmContainerName: 'axixpoctfstate'
        backendAzureRmKey: 'poc.tfstate'


- stage:
  displayName: tera_validate

  jobs:
  - job: terraformvalidate
    displayName: tera_validate

    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        backendServiceArm: 'axis-terraform-connection'
        backendAzureRmResourceGroupName: 'axis-sbx-poc-rg'
        backendAzureRmStorageAccountName: 'axissbxpocst01'
        backendAzureRmContainerName: 'axixpoctfstate'
        backendAzureRmKey: 'poc.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)'


- stage:
  displayName: tera_plan

  jobs:
  - job: terraformplan
    displayName: tera_plan

    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        backendServiceArm: 'axis-terraform-connection'
        backendAzureRmResourceGroupName: 'axis-sbx-poc-rg'
        backendAzureRmStorageAccountName: 'axissbxpocst01'
        backendAzureRmContainerName: 'axixpoctfstate'
        backendAzureRmKey: 'poc.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        environmentServiceNameAzureRM: 'axis-terraform-connection'